[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "weather-helper"
version = "0.1.0"
description = "A simple weather helper application."
dependencies = [
    "pytz==2025.2",
    "pytest==8.3.5",
    "requests==2.32.3",
    "pyinstaller==6.14.1"
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]
testpaths = [
    "tests"
]
python_files = [
    "test_*.py"
]