name: Build Executable on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.4'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # TODO: Add unit tests
      # - name: Run unit tests
      #   run: |
      #     pytest

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed weather_helper.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-executable
          path: dist/WeatherHelper.exe
