name: Test and Build Executable on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        os: [windows-2022]
        include:
          - os: windows-2022
            executable_name: weather_helper.exe
          - os: ubuntu-22.04
            executable_name: weather_helper
          - os: macos-12
            executable_name: weather_helper
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: |
          pytest

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed weather_helper.py

      - name: Create Tag
        if: matrix.os == 'windows-2022'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ github.event.pull_request.number }}" -m "Release v${{ github.event.pull_request.number }}"
          git push origin "v${{ github.event.pull_request.number }}"

      - name: Create Release
        id: create_release
        if: matrix.os == 'windows-2022'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.pull_request.number }}
          name: Release v${{ github.event.pull_request.number }}
          body: |
            Release from PR #${{ github.event.pull_request.number }}
            ${{ github.event.pull_request.title }}

            This release includes executables for:
            - Windows
            - Linux
            - macOS
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ matrix.executable_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
