name: Build and Release Executable

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Unit Tests
        run: |
          pytest

      - name: Determine Next Version
        id: semver
        uses: bitshifted/git-auto-semver@v1.1.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build Executable
        run: |
          pyinstaller --onefile --windowed weather_helper.py

      - name: Package Executable
        run: |
          Compress-Archive -Path dist\weather_helper.exe -DestinationPath dist\weather_helper.zip

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create Git Tag
        run: |
          git tag -a "${{ steps.semver.outputs.version }}" -m "Release ${{ steps.semver.outputs.version }}"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          git push origin "${{ steps.semver.outputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.version }}
          name: Release ${{ steps.semver.outputs.version }}
          body: |
            Release from PR #${{ github.event.pull_request.number }}
            ${{ github.event.pull_request.title }}

            This release includes:
            - Windows Executable
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/weather_helper.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
